VERSION: 2
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 18
  ROI_HEADS:
    NUM_CLASSES: 2
  RPN:
    PRE_NMS_TOPK_TRAIN: 200
    PRE_NMS_TOPK_TEST: 100
    POST_NMS_TOPK_TRAIN: 100
    POST_NMS_TOPK_TEST: 100
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 320
DATASETS:
  TRAIN: ('pascal_nlab_trainval',)
  TEST: ('pascal_nlab_test',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100
DATALOADER:
  NUM_WORKERS: 0
TEST:
  DETECTIONS_PER_IMAGE: 4
