VERSION: 2
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 0
  MASK_ON: False
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  ROI_HEADS:
    NUM_CLASSES: 2
  RPN:
    PRE_NMS_TOPK_TEST: 100
    POST_NMS_TOPK_TEST: 100
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 320
DATASETS:
  TRAIN: ('pascal_nlab_trainval',)
  TEST: ('pascal_nlab_test',)
SOLVER:
  STEPS: (24000, 28000)
  MAX_ITER: 32000  # Training from scratch takes longer to converge
  WARMUP_ITERS: 2000
  BASE_LR: 0.02
DATALOADER:
  NUM_WORKERS: 0
TEST:
  DETECTIONS_PER_IMAGE: 4
